PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS historical_archive_props (
  historical_archive_prop_id INTEGER PRIMARY KEY AUTOINCREMENT,
  archive_version TEXT NOT NULL DEFAULT 'historical-archive-v1',
  board_date TEXT NOT NULL,
  pitcher_name TEXT NOT NULL,
  team_abbreviation TEXT NOT NULL,
  opponent_abbreviation TEXT NOT NULL,
  pitcher_hand TEXT,
  prop_line REAL NOT NULL,
  original_side TEXT,
  actual_strikeouts INTEGER,
  market_result TEXT NOT NULL,
  source_workbook TEXT NOT NULL,
  source_url TEXT,
  source_quality TEXT NOT NULL DEFAULT 'ARCHIVED_TRACKER',
  eligible_for_reconstruction INTEGER NOT NULL DEFAULT 1 CHECK (eligible_for_reconstruction IN (0,1)),
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(board_date,pitcher_name,team_abbreviation,opponent_abbreviation,prop_line)
);

CREATE INDEX IF NOT EXISTS idx_historical_archive_props_date
  ON historical_archive_props(board_date,historical_archive_prop_id);
CREATE INDEX IF NOT EXISTS idx_historical_archive_props_eligible
  ON historical_archive_props(eligible_for_reconstruction,board_date);

INSERT OR IGNORE INTO historical_archive_props(board_date,pitcher_name,team_abbreviation,opponent_abbreviation,pitcher_hand,prop_line,original_side,actual_strikeouts,market_result,source_workbook,source_url) VALUES ('2026-07-08','Dylan Cease','TOR','SF','R',7.0,'More',11,'Over','mlb_k_props_tracker_master_2026-07-09_results.xlsx','https://www.statmuse.com/mlb/ask/pitchers-with-the-most-strikeouts-today');
INSERT OR IGNORE INTO historical_archive_props(board_date,pitcher_name,team_abbreviation,opponent_abbreviation,pitcher_hand,prop_line,original_side,actual_strikeouts,market_result,source_workbook,source_url) VALUES ('2026-07-08','Logan Webb','SF','TOR','R',5.0,'More',2,'Under','mlb_k_props_tracker_master_2026-07-09_results.xlsx','https://www.statmuse.com/mlb/ask/logan-webb-strikeouts-last-10-games');
INSERT OR IGNORE INTO historical_archive_props(board_date,pitcher_name,team_abbreviation,opponent_abbreviation,pitcher_hand,prop_line,original_side,actual_strikeouts,market_result,source_workbook,source_url) VALUES ('2026-07-08','Dean Kremer','BAL','CHC','R',5.0,'More',4,'Under','mlb_k_props_tracker_master_2026-07-09_results.xlsx','https://www.statmuse.com/mlb/ask/pitchers-with-the-most-strikeouts-today');
INSERT OR IGNORE INTO historical_archive_props(board_date,pitcher_name,team_abbreviation,opponent_abbreviation,pitcher_hand,prop_line,original_side,actual_strikeouts,market_result,source_workbook,source_url) VALUES ('2026-07-08','Colin Rea','CHC','BAL','R',4.0,'More',2,'Under','mlb_k_props_tracker_master_2026-07-09_results.xlsx','https://www.statmuse.com/mlb/ask/colin-rea-last-10-games');
INSERT OR IGNORE INTO historical_archive_props(board_date,pitcher_name,team_abbreviation,opponent_abbreviation,pitcher_hand,prop_line,original_side,actual_strikeouts,market_result,source_workbook,source_url) VALUES ('2026-07-08','George Kirby','SEA','MIA','R',5.0,'More',7,'Over','mlb_k_props_tracker_master_2026-07-09_results.xlsx','https://www.statmuse.com/mlb/ask/pitchers-with-the-most-strikeouts-today');
INSERT OR IGNORE INTO historical_archive_props(board_date,pitcher_name,team_abbreviation,opponent_abbreviation,pitcher_hand,prop_line,original_side,actual_strikeouts,market_result,source_workbook,source_url) VALUES ('2026-07-08','Tyler Phillips','MIA','SEA','R',4.5,'More',3,'Under','mlb_k_props_tracker_master_2026-07-09_results.xlsx','https://www.statmuse.com/mlb/ask/tyler-phillips-last-10-games');
INSERT OR IGNORE INTO historical_archive_props(board_date,pitcher_name,team_abbreviation,opponent_abbreviation,pitcher_hand,prop_line,original_side,actual_strikeouts,market_result,source_workbook,source_url) VALUES ('2026-07-08','Jared Jones','PIT','ATL','R',5.0,'More',8,'Over','mlb_k_props_tracker_master_2026-07-09_results.xlsx','https://www.statmuse.com/mlb/ask/pitchers-with-the-most-strikeouts-today');
INSERT OR IGNORE INTO historical_archive_props(board_date,pitcher_name,team_abbreviation,opponent_abbreviation,pitcher_hand,prop_line,original_side,actual_strikeouts,market_result,source_workbook,source_url) VALUES ('2026-07-08','Gerrit Cole','NYY','TB','R',5.0,'More',6,'Over','mlb_k_props_tracker_master_2026-07-09_results.xlsx','https://www.statmuse.com/mlb/ask/pitchers-with-the-most-strikeouts-today');
INSERT OR IGNORE INTO historical_archive_props(board_date,pitcher_name,team_abbreviation,opponent_abbreviation,pitcher_hand,prop_line,original_side,actual_strikeouts,market_result,source_workbook,source_url) VALUES ('2026-07-08','Shane McClanahan','TB','NYY','L',5.5,'More',5,'Under','mlb_k_props_tracker_master_2026-07-09_results.xlsx','https://www.statmuse.com/mlb/ask/pitchers-with-the-most-strikeouts-today');
INSERT OR IGNORE INTO historical_archive_props(board_date,pitcher_name,team_abbreviation,opponent_abbreviation,pitcher_hand,prop_line,original_side,actual_strikeouts,market_result,source_workbook,source_url) VALUES ('2026-07-08','Grant Holmes','ATL','PIT','R',4.5,'More',5,'Over','mlb_k_props_tracker_master_2026-07-09_results.xlsx','https://www.statmuse.com/mlb/ask/pitchers-with-the-most-strikeouts-today');
INSERT OR IGNORE INTO historical_archive_props(board_date,pitcher_name,team_abbreviation,opponent_abbreviation,pitcher_hand,prop_line,original_side,actual_strikeouts,market_result,source_workbook,source_url) VALUES ('2026-07-08','Troy Melton','DET','ATH','R',5.0,'More',9,'Over','mlb_k_props_tracker_master_2026-07-09_results.xlsx','https://www.statmuse.com/mlb/ask/pitchers-with-the-most-strikeouts-today');
INSERT OR IGNORE INTO historical_archive_props(board_date,pitcher_name,team_abbreviation,opponent_abbreviation,pitcher_hand,prop_line,original_side,actual_strikeouts,market_result,source_workbook,source_url) VALUES ('2026-07-08','Jeffrey Springs','ATH','DET','L',4.5,'More',4,'Under','mlb_k_props_tracker_master_2026-07-09_results.xlsx','https://www.statmuse.com/mlb/ask/pitchers-with-the-most-strikeouts-today');
INSERT OR IGNORE INTO historical_archive_props(board_date,pitcher_name,team_abbreviation,opponent_abbreviation,pitcher_hand,prop_line,original_side,actual_strikeouts,market_result,source_workbook,source_url) VALUES ('2026-07-08','Foster Griffin','WSH','HOU','L',5.0,'More',9,'Over','mlb_k_props_tracker_master_2026-07-09_results.xlsx','https://www.statmuse.com/mlb/ask/pitchers-with-the-most-strikeouts-today');
INSERT OR IGNORE INTO historical_archive_props(board_date,pitcher_name,team_abbreviation,opponent_abbreviation,pitcher_hand,prop_line,original_side,actual_strikeouts,market_result,source_workbook,source_url) VALUES ('2026-07-08','Spencer Arrighetti','HOU','WSH','R',4.5,'More',2,'Under','mlb_k_props_tracker_master_2026-07-09_results.xlsx','https://www.statmuse.com/mlb/ask/spencer-arrighetti-stats-last-10-games');
INSERT OR IGNORE INTO historical_archive_props(board_date,pitcher_name,team_abbreviation,opponent_abbreviation,pitcher_hand,prop_line,original_side,actual_strikeouts,market_result,source_workbook,source_url) VALUES ('2026-07-08','Chase Burns','CIN','PHI','R',7.0,'More',2,'Under','mlb_k_props_tracker_master_2026-07-09_results.xlsx','https://www.statmuse.com/mlb/ask/chase-burns-strike-outs-last-5-games');
INSERT OR IGNORE INTO historical_archive_props(board_date,pitcher_name,team_abbreviation,opponent_abbreviation,pitcher_hand,prop_line,original_side,actual_strikeouts,market_result,source_workbook,source_url) VALUES ('2026-07-08','Christian Scott','NYM','KC','R',5.5,'More',5,'Under','mlb_k_props_tracker_master_2026-07-09_results.xlsx','https://www.statmuse.com/mlb/ask/pitchers-with-the-most-strikeouts-today');
INSERT OR IGNORE INTO historical_archive_props(board_date,pitcher_name,team_abbreviation,opponent_abbreviation,pitcher_hand,prop_line,original_side,actual_strikeouts,market_result,source_workbook,source_url) VALUES ('2026-07-08','Steven Cruz','KC','NYM','R',1.5,'More',2,'Over','mlb_k_props_tracker_master_2026-07-09_results.xlsx','https://www.statmuse.com/mlb/ask/starting-right-handed-pitchers-game-log-vs-mets');
INSERT OR IGNORE INTO historical_archive_props(board_date,pitcher_name,team_abbreviation,opponent_abbreviation,pitcher_hand,prop_line,original_side,actual_strikeouts,market_result,source_workbook,source_url) VALUES ('2026-07-08','Slade Cecconi','CLE','MIN','R',4.0,'More',4,'Push','mlb_k_props_tracker_master_2026-07-09_results.xlsx','https://www.statmuse.com/mlb/ask/pitchers-with-the-most-strikeouts-today');
INSERT OR IGNORE INTO historical_archive_props(board_date,pitcher_name,team_abbreviation,opponent_abbreviation,pitcher_hand,prop_line,original_side,actual_strikeouts,market_result,source_workbook,source_url) VALUES ('2026-07-08','Davis Martin','CWS','BOS','R',4.5,'More',2,'Under','mlb_k_props_tracker_master_2026-07-09_results.xlsx','https://www.statmuse.com/mlb/ask/davis-martin-each-game-stats-strikeouts');
INSERT OR IGNORE INTO historical_archive_props(board_date,pitcher_name,team_abbreviation,opponent_abbreviation,pitcher_hand,prop_line,original_side,actual_strikeouts,market_result,source_workbook,source_url) VALUES ('2026-07-08','Jake Bennett','BOS','CWS','L',4.0,'More',4,'Push','mlb_k_props_tracker_master_2026-07-09_results.xlsx','https://www.statmuse.com/mlb/ask/pitchers-with-the-most-strikeouts-today');
INSERT OR IGNORE INTO historical_archive_props(board_date,pitcher_name,team_abbreviation,opponent_abbreviation,pitcher_hand,prop_line,original_side,actual_strikeouts,market_result,source_workbook,source_url) VALUES ('2026-07-08','Connor Prielipp','MIN','CLE','L',6.0,'More',6,'Push','mlb_k_props_tracker_master_2026-07-09_results.xlsx','https://www.statmuse.com/mlb/ask/pitchers-with-the-most-strikeouts-today');
INSERT OR IGNORE INTO historical_archive_props(board_date,pitcher_name,team_abbreviation,opponent_abbreviation,pitcher_hand,prop_line,original_side,actual_strikeouts,market_result,source_workbook,source_url) VALUES ('2026-07-08','Kyle Harrison','MIL','STL','L',5.0,'More',2,'Under','mlb_k_props_tracker_master_2026-07-09_results.xlsx','https://www.statmuse.com/mlb/ask/kyle-harrison-stats-last-10-games-by-game');
INSERT OR IGNORE INTO historical_archive_props(board_date,pitcher_name,team_abbreviation,opponent_abbreviation,pitcher_hand,prop_line,original_side,actual_strikeouts,market_result,source_workbook,source_url) VALUES ('2026-07-08','Michael McGreevy','STL','MIL','R',3.5,'More',6,'Over','mlb_k_props_tracker_master_2026-07-09_results.xlsx','https://www.statmuse.com/mlb/ask/pitchers-with-the-most-strikeouts-today');
INSERT OR IGNORE INTO historical_archive_props(board_date,pitcher_name,team_abbreviation,opponent_abbreviation,pitcher_hand,prop_line,original_side,actual_strikeouts,market_result,source_workbook,source_url) VALUES ('2026-07-08','MacKenzie Gore','TEX','LAA','L',6.5,'More',7,'Over','mlb_k_props_tracker_master_2026-07-09_results.xlsx','https://www.statmuse.com/mlb/ask/pitchers-with-the-most-strikeouts-today');
INSERT OR IGNORE INTO historical_archive_props(board_date,pitcher_name,team_abbreviation,opponent_abbreviation,pitcher_hand,prop_line,original_side,actual_strikeouts,market_result,source_workbook,source_url) VALUES ('2026-07-08','Walbert Ureña','LAA','TEX','R',4.5,'More',3,'Under','mlb_k_props_tracker_master_2026-07-09_results.xlsx','https://www.statmuse.com/mlb/ask?q=walbert+ure%C3%B1a+innings+pitched+when+starting+2026');
INSERT OR IGNORE INTO historical_archive_props(board_date,pitcher_name,team_abbreviation,opponent_abbreviation,pitcher_hand,prop_line,original_side,actual_strikeouts,market_result,source_workbook,source_url) VALUES ('2026-07-08','Roki Sasaki','LAD','COL','R',5.5,'More',5,'Under','mlb_k_props_tracker_master_2026-07-09_results.xlsx','https://www.statmuse.com/mlb/ask/pitchers-with-the-most-strikeouts-today');
INSERT OR IGNORE INTO historical_archive_props(board_date,pitcher_name,team_abbreviation,opponent_abbreviation,pitcher_hand,prop_line,original_side,actual_strikeouts,market_result,source_workbook,source_url) VALUES ('2026-07-08','Michael King','SD','AZ','R',4.5,'More',4,'Under','mlb_k_props_tracker_master_2026-07-09_results.xlsx','https://www.statmuse.com/mlb/ask/pitchers-with-the-most-strikeouts-today');
INSERT OR IGNORE INTO historical_archive_props(board_date,pitcher_name,team_abbreviation,opponent_abbreviation,pitcher_hand,prop_line,original_side,actual_strikeouts,market_result,source_workbook,source_url) VALUES ('2026-07-08','Jose Cabrera','AZ','SD','R',3.5,'More',2,'Under','mlb_k_props_tracker_master_2026-07-09_results.xlsx','https://www.statmuse.com/mlb/ask/starting-right-hand-pitchers-vs-padres-game-log');
INSERT OR IGNORE INTO historical_archive_props(board_date,pitcher_name,team_abbreviation,opponent_abbreviation,pitcher_hand,prop_line,original_side,actual_strikeouts,market_result,source_workbook,source_url) VALUES ('2026-07-09','Mitch Keller','PIT','ATL','R',4.0,'More',3,'Under','mlb_k_props_tracker_master_2026-07-10_results.xlsx','https://www.espn.com/mlb/stats/dailyleaders/_/type/pitching/sort/avgGameScore/league/nl');
INSERT OR IGNORE INTO historical_archive_props(board_date,pitcher_name,team_abbreviation,opponent_abbreviation,pitcher_hand,prop_line,original_side,actual_strikeouts,market_result,source_workbook,source_url) VALUES ('2026-07-09','Bryce Elder','ATL','PIT','R',4.5,'More',3,'Under','mlb_k_props_tracker_master_2026-07-10_results.xlsx','https://www.espn.com/mlb/stats/dailyleaders/_/type/pitching/sort/avgGameScore/league/nl');
INSERT OR IGNORE INTO historical_archive_props(board_date,pitcher_name,team_abbreviation,opponent_abbreviation,pitcher_hand,prop_line,original_side,actual_strikeouts,market_result,source_workbook,source_url) VALUES ('2026-07-09','Sean Manaea','NYM','KC','L',5.0,'More',6,'Over','mlb_k_props_tracker_master_2026-07-10_results.xlsx','https://www.espn.com/mlb/stats/dailyleaders/_/type/pitching/sort/avgGameScore/league/nl');
INSERT OR IGNORE INTO historical_archive_props(board_date,pitcher_name,team_abbreviation,opponent_abbreviation,pitcher_hand,prop_line,original_side,actual_strikeouts,market_result,source_workbook,source_url) VALUES ('2026-07-09','Drew Rasmussen','TB','NYY','R',6.0,'More',2,'Under','mlb_k_props_tracker_master_2026-07-10_results.xlsx','https://www.espn.com/mlb/stats/dailyleaders/_/type/pitching/sort/avgGameScore/league/al');
INSERT OR IGNORE INTO historical_archive_props(board_date,pitcher_name,team_abbreviation,opponent_abbreviation,pitcher_hand,prop_line,original_side,actual_strikeouts,market_result,source_workbook,source_url) VALUES ('2026-07-09','Michael Wacha','KC','NYM','R',5.0,'More',5,'Push','mlb_k_props_tracker_master_2026-07-10_results.xlsx','https://www.espn.com/mlb/stats/dailyleaders/_/type/pitching/sort/avgGameScore/league/al');
INSERT OR IGNORE INTO historical_archive_props(board_date,pitcher_name,team_abbreviation,opponent_abbreviation,pitcher_hand,prop_line,original_side,actual_strikeouts,market_result,source_workbook,source_url) VALUES ('2026-07-09','David Peterson','CHC','BAL','L',4.0,'More',2,'Under','mlb_k_props_tracker_master_2026-07-10_results.xlsx','https://www.espn.com/mlb/stats/dailyleaders/_/type/pitching/sort/avgGameScore/league/nl');
INSERT OR IGNORE INTO historical_archive_props(board_date,pitcher_name,team_abbreviation,opponent_abbreviation,pitcher_hand,prop_line,original_side,actual_strikeouts,market_result,source_workbook,source_url) VALUES ('2026-07-09','Bailey Ober','MIN','CLE','R',4.0,'More',5,'Over','mlb_k_props_tracker_master_2026-07-10_results.xlsx','https://www.espn.com/mlb/stats/dailyleaders/_/type/pitching/sort/avgGameScore/league/al');
INSERT OR IGNORE INTO historical_archive_props(board_date,pitcher_name,team_abbreviation,opponent_abbreviation,pitcher_hand,prop_line,original_side,actual_strikeouts,market_result,source_workbook,source_url) VALUES ('2026-07-09','Gavin Williams','CLE','MIN','R',6.0,'More',11,'Over','mlb_k_props_tracker_master_2026-07-10_results.xlsx','https://www.espn.com/mlb/stats/dailyleaders/_/type/pitching/sort/avgGameScore/league/al');
INSERT OR IGNORE INTO historical_archive_props(board_date,pitcher_name,team_abbreviation,opponent_abbreviation,pitcher_hand,prop_line,original_side,actual_strikeouts,market_result,source_workbook,source_url) VALUES ('2026-07-09','Anthony Kay','CWS','BOS','L',4.0,'More',4,'Push','mlb_k_props_tracker_master_2026-07-10_results.xlsx','https://www.espn.com/mlb/stats/dailyleaders/_/type/pitching/sort/avgGameScore/league/al');
INSERT OR IGNORE INTO historical_archive_props(board_date,pitcher_name,team_abbreviation,opponent_abbreviation,pitcher_hand,prop_line,original_side,actual_strikeouts,market_result,source_workbook,source_url) VALUES ('2026-07-09','Patrick Sandoval','BOS','CWS','L',4.5,'More',5,'Over','mlb_k_props_tracker_master_2026-07-10_results.xlsx','https://www.espn.com/mlb/stats/dailyleaders/_/type/pitching/sort/avgGameScore/league/al');
INSERT OR IGNORE INTO historical_archive_props(board_date,pitcher_name,team_abbreviation,opponent_abbreviation,pitcher_hand,prop_line,original_side,actual_strikeouts,market_result,source_workbook,source_url) VALUES ('2026-07-09','Trevor Rogers','BAL','CHC','L',4.5,'More',4,'Under','mlb_k_props_tracker_master_2026-07-10_results.xlsx','https://www.espn.com/mlb/stats/dailyleaders/_/type/pitching/sort/avgGameScore/league/al');
INSERT OR IGNORE INTO historical_archive_props(board_date,pitcher_name,team_abbreviation,opponent_abbreviation,pitcher_hand,prop_line,original_side,actual_strikeouts,market_result,source_workbook,source_url) VALUES ('2026-07-09','Bryce Miller','SEA','MIA','R',6.0,'More',3,'Under','mlb_k_props_tracker_master_2026-07-10_results.xlsx','https://www.espn.com/mlb/stats/dailyleaders/_/type/pitching/sort/avgGameScore/league/al');
INSERT OR IGNORE INTO historical_archive_props(board_date,pitcher_name,team_abbreviation,opponent_abbreviation,pitcher_hand,prop_line,original_side,actual_strikeouts,market_result,source_workbook,source_url) VALUES ('2026-07-09','Framber Valdez','DET','ATH','L',5.0,'More',9,'Over','mlb_k_props_tracker_master_2026-07-10_results.xlsx','https://www.espn.com/mlb/stats/dailyleaders/_/type/pitching/sort/avgGameScore/league/al');
INSERT OR IGNORE INTO historical_archive_props(board_date,pitcher_name,team_abbreviation,opponent_abbreviation,pitcher_hand,prop_line,original_side,actual_strikeouts,market_result,source_workbook,source_url) VALUES ('2026-07-09','Janson Junk','MIA','SEA','R',3.5,'More',5,'Over','mlb_k_props_tracker_master_2026-07-10_results.xlsx','https://www.espn.com/mlb/stats/dailyleaders/_/type/pitching/sort/avgGameScore/league/nl');
INSERT OR IGNORE INTO historical_archive_props(board_date,pitcher_name,team_abbreviation,opponent_abbreviation,pitcher_hand,prop_line,original_side,actual_strikeouts,market_result,source_workbook,source_url) VALUES ('2026-07-09','Jack Perkins','ATH','DET','R',5.5,'More',NULL,'Void','mlb_k_props_tracker_master_2026-07-10_results.xlsx','https://www.espn.com/mlb/recap/_/gameId/401816083');
INSERT OR IGNORE INTO historical_archive_props(board_date,pitcher_name,team_abbreviation,opponent_abbreviation,pitcher_hand,prop_line,original_side,actual_strikeouts,market_result,source_workbook,source_url) VALUES ('2026-07-09','Brady Singer','CIN','PHI','R',5.0,'More',5,'Push','mlb_k_props_tracker_master_2026-07-10_results.xlsx','https://www.espn.com/mlb/stats/dailyleaders/_/type/pitching/sort/avgGameScore/league/nl');
INSERT OR IGNORE INTO historical_archive_props(board_date,pitcher_name,team_abbreviation,opponent_abbreviation,pitcher_hand,prop_line,original_side,actual_strikeouts,market_result,source_workbook,source_url) VALUES ('2026-07-09','Jesús Luzardo','PHI','CIN','L',7.5,'More',11,'Over','mlb_k_props_tracker_master_2026-07-10_results.xlsx','https://www.espn.com/mlb/stats/dailyleaders/_/type/pitching/sort/avgGameScore/league/nl');
INSERT OR IGNORE INTO historical_archive_props(board_date,pitcher_name,team_abbreviation,opponent_abbreviation,pitcher_hand,prop_line,original_side,actual_strikeouts,market_result,source_workbook,source_url) VALUES ('2026-07-09','Andre Pallante','STL','MIL','R',4.0,'More',2,'Under','mlb_k_props_tracker_master_2026-07-10_results.xlsx','https://www.espn.com/mlb/stats/dailyleaders/_/type/pitching/sort/avgGameScore/league/nl');
INSERT OR IGNORE INTO historical_archive_props(board_date,pitcher_name,team_abbreviation,opponent_abbreviation,pitcher_hand,prop_line,original_side,actual_strikeouts,market_result,source_workbook,source_url) VALUES ('2026-07-09','Logan Henderson','MIL','STL','R',5.5,'More',4,'Under','mlb_k_props_tracker_master_2026-07-10_results.xlsx','https://www.espn.com/mlb/stats/dailyleaders/_/type/pitching/sort/avgGameScore/league/nl');
INSERT OR IGNORE INTO historical_archive_props(board_date,pitcher_name,team_abbreviation,opponent_abbreviation,pitcher_hand,prop_line,original_side,actual_strikeouts,market_result,source_workbook,source_url) VALUES ('2026-07-09','Nathan Eovaldi','TEX','LAA','R',7.0,'More',10,'Over','mlb_k_props_tracker_master_2026-07-10_results.xlsx','https://www.espn.com/mlb/stats/dailyleaders/_/type/pitching/sort/avgGameScore/league/al');
INSERT OR IGNORE INTO historical_archive_props(board_date,pitcher_name,team_abbreviation,opponent_abbreviation,pitcher_hand,prop_line,original_side,actual_strikeouts,market_result,source_workbook,source_url) VALUES ('2026-07-09','Reid Detmers','LAA','TEX','L',6.0,'More',6,'Push','mlb_k_props_tracker_master_2026-07-10_results.xlsx','https://www.espn.com/mlb/stats/dailyleaders/_/type/pitching/sort/avgGameScore/league/al');
INSERT OR IGNORE INTO historical_archive_props(board_date,pitcher_name,team_abbreviation,opponent_abbreviation,pitcher_hand,prop_line,original_side,actual_strikeouts,market_result,source_workbook,source_url) VALUES ('2026-07-09','Merrill Kelly','AZ','SD','R',4.0,'More',6,'Over','mlb_k_props_tracker_master_2026-07-10_results.xlsx','https://www.espn.com/mlb/stats/dailyleaders/_/type/pitching/sort/avgGameScore/league/nl');
INSERT OR IGNORE INTO historical_archive_props(board_date,pitcher_name,team_abbreviation,opponent_abbreviation,pitcher_hand,prop_line,original_side,actual_strikeouts,market_result,source_workbook,source_url) VALUES ('2026-07-09','Griffin Canning','SD','AZ','R',4.0,'More',5,'Over','mlb_k_props_tracker_master_2026-07-10_results.xlsx','https://www.espn.com/mlb/stats/dailyleaders/_/type/pitching/sort/avgGameScore/league/nl');
INSERT OR IGNORE INTO historical_archive_props(board_date,pitcher_name,team_abbreviation,opponent_abbreviation,pitcher_hand,prop_line,original_side,actual_strikeouts,market_result,source_workbook,source_url) VALUES ('2026-07-09','Ryan Feltner','COL','SF','R',4.0,'More',3,'Under','mlb_k_props_tracker_master_2026-07-10_results.xlsx','https://www.espn.com/mlb/stats/dailyleaders/_/type/pitching/sort/avgGameScore/league/nl');
INSERT OR IGNORE INTO historical_archive_props(board_date,pitcher_name,team_abbreviation,opponent_abbreviation,pitcher_hand,prop_line,original_side,actual_strikeouts,market_result,source_workbook,source_url) VALUES ('2026-07-17','Jake Bennett','BOS','TB','L',3.5,NULL,3,'Under','tracker_master_closed_2026-07-18.xlsx','https://www.cbssports.com/mlb/gametracker/live/MLB_20260717_TB%40BOS/');
INSERT OR IGNORE INTO historical_archive_props(board_date,pitcher_name,team_abbreviation,opponent_abbreviation,pitcher_hand,prop_line,original_side,actual_strikeouts,market_result,source_workbook,source_url) VALUES ('2026-07-17','Gerrit Cole','NYY','LAD','R',5.0,NULL,8,'Over','tracker_master_closed_2026-07-18.xlsx','https://www.cbssports.com/mlb/gametracker/boxscore/MLB_20260717_LAD%40NYY/');
INSERT OR IGNORE INTO historical_archive_props(board_date,pitcher_name,team_abbreviation,opponent_abbreviation,pitcher_hand,prop_line,original_side,actual_strikeouts,market_result,source_workbook,source_url) VALUES ('2026-07-17','Roki Sasaki','LAD','NYY','R',5.0,NULL,5,'Push','tracker_master_closed_2026-07-18.xlsx','https://www.cbssports.com/mlb/gametracker/boxscore/MLB_20260717_LAD%40NYY/');
INSERT OR IGNORE INTO historical_archive_props(board_date,pitcher_name,team_abbreviation,opponent_abbreviation,pitcher_hand,prop_line,original_side,actual_strikeouts,market_result,source_workbook,source_url) VALUES ('2026-07-17','Gavin Williams','CLE','PIT','R',7.0,NULL,NULL,'Void','tracker_master_closed_2026-07-18.xlsx','https://www.cbssports.com/mlb/gametracker/preview/MLB_20260717_PIT%40CLE/');
INSERT OR IGNORE INTO historical_archive_props(board_date,pitcher_name,team_abbreviation,opponent_abbreviation,pitcher_hand,prop_line,original_side,actual_strikeouts,market_result,source_workbook,source_url) VALUES ('2026-07-17','Jared Jones','PIT','CLE','R',5.5,NULL,NULL,'Void','tracker_master_closed_2026-07-18.xlsx','https://www.cbssports.com/mlb/gametracker/preview/MLB_20260717_PIT%40CLE/');
INSERT OR IGNORE INTO historical_archive_props(board_date,pitcher_name,team_abbreviation,opponent_abbreviation,pitcher_hand,prop_line,original_side,actual_strikeouts,market_result,source_workbook,source_url) VALUES ('2026-07-17','Chris Sale','ATL','TEX','L',7.0,NULL,6,'Under','tracker_master_closed_2026-07-18.xlsx','https://www.cbssports.com/mlb/gametracker/live/MLB_20260717_TEX%40ATL/');
INSERT OR IGNORE INTO historical_archive_props(board_date,pitcher_name,team_abbreviation,opponent_abbreviation,pitcher_hand,prop_line,original_side,actual_strikeouts,market_result,source_workbook,source_url) VALUES ('2026-07-17','Cal Quantrill','TEX','ATL','R',3.5,NULL,3,'Under','tracker_master_closed_2026-07-18.xlsx','https://www.cbssports.com/mlb/gametracker/live/MLB_20260717_TEX%40ATL/');
INSERT OR IGNORE INTO historical_archive_props(board_date,pitcher_name,team_abbreviation,opponent_abbreviation,pitcher_hand,prop_line,original_side,actual_strikeouts,market_result,source_workbook,source_url) VALUES ('2026-07-17','Spencer Miles','TOR','CWS','R',4.0,NULL,4,'Push','tracker_master_closed_2026-07-18.xlsx','https://www.cbssports.com/mlb/gametracker/live/MLB_20260717_CHW%40TOR/');
INSERT OR IGNORE INTO historical_archive_props(board_date,pitcher_name,team_abbreviation,opponent_abbreviation,pitcher_hand,prop_line,original_side,actual_strikeouts,market_result,source_workbook,source_url) VALUES ('2026-07-17','Anthony Kay','CWS','TOR','L',3.5,NULL,5,'Over','tracker_master_closed_2026-07-18.xlsx','https://www.cbssports.com/mlb/gametracker/live/MLB_20260717_CHW%40TOR/');
INSERT OR IGNORE INTO historical_archive_props(board_date,pitcher_name,team_abbreviation,opponent_abbreviation,pitcher_hand,prop_line,original_side,actual_strikeouts,market_result,source_workbook,source_url) VALUES ('2026-07-17','Sandy Alcantara','MIA','MIL','R',5.0,NULL,7,'Over','tracker_master_closed_2026-07-18.xlsx','https://www.cbssports.com/mlb/gametracker/live/MLB_20260717_MIA%40MIL/');
INSERT OR IGNORE INTO historical_archive_props(board_date,pitcher_name,team_abbreviation,opponent_abbreviation,pitcher_hand,prop_line,original_side,actual_strikeouts,market_result,source_workbook,source_url) VALUES ('2026-07-17','Logan Henderson','MIL','MIA','R',5.0,NULL,4,'Under','tracker_master_closed_2026-07-18.xlsx','https://www.cbssports.com/mlb/gametracker/live/MLB_20260717_MIA%40MIL/');
INSERT OR IGNORE INTO historical_archive_props(board_date,pitcher_name,team_abbreviation,opponent_abbreviation,pitcher_hand,prop_line,original_side,actual_strikeouts,market_result,source_workbook,source_url) VALUES ('2026-07-17','Bailey Ober','MIN','CHC','R',4.0,NULL,7,'Over','tracker_master_closed_2026-07-18.xlsx','https://www.cbssports.com/mlb/gametracker/live/MLB_20260717_MIN%40CHC/');
INSERT OR IGNORE INTO historical_archive_props(board_date,pitcher_name,team_abbreviation,opponent_abbreviation,pitcher_hand,prop_line,original_side,actual_strikeouts,market_result,source_workbook,source_url) VALUES ('2026-07-17','Colin Rea','CHC','MIN','R',3.5,NULL,6,'Over','tracker_master_closed_2026-07-18.xlsx','https://www.cbssports.com/mlb/gametracker/live/MLB_20260717_MIN%40CHC/');
INSERT OR IGNORE INTO historical_archive_props(board_date,pitcher_name,team_abbreviation,opponent_abbreviation,pitcher_hand,prop_line,original_side,actual_strikeouts,market_result,source_workbook,source_url) VALUES ('2026-07-17','Peter Lambert','HOU','BAL','R',5.5,NULL,10,'Over','tracker_master_closed_2026-07-18.xlsx','https://www.cbssports.com/mlb/gametracker/live/MLB_20260717_BAL%40HOU/');
INSERT OR IGNORE INTO historical_archive_props(board_date,pitcher_name,team_abbreviation,opponent_abbreviation,pitcher_hand,prop_line,original_side,actual_strikeouts,market_result,source_workbook,source_url) VALUES ('2026-07-17','Dean Kremer','BAL','HOU','R',5.0,NULL,5,'Push','tracker_master_closed_2026-07-18.xlsx','https://www.cbssports.com/mlb/gametracker/live/MLB_20260717_BAL%40HOU/');
INSERT OR IGNORE INTO historical_archive_props(board_date,pitcher_name,team_abbreviation,opponent_abbreviation,pitcher_hand,prop_line,original_side,actual_strikeouts,market_result,source_workbook,source_url) VALUES ('2026-07-17','Michael King','SD','KC','R',4.0,NULL,4,'Push','tracker_master_closed_2026-07-18.xlsx','https://www.cbssports.com/mlb/gametracker/live/MLB_20260717_SD%40KC/');
INSERT OR IGNORE INTO historical_archive_props(board_date,pitcher_name,team_abbreviation,opponent_abbreviation,pitcher_hand,prop_line,original_side,actual_strikeouts,market_result,source_workbook,source_url) VALUES ('2026-07-17','Seth Lugo','KC','SD','R',4.0,NULL,3,'Under','tracker_master_closed_2026-07-18.xlsx','https://www.cbssports.com/mlb/gametracker/live/MLB_20260717_SD%40KC/');
INSERT OR IGNORE INTO historical_archive_props(board_date,pitcher_name,team_abbreviation,opponent_abbreviation,pitcher_hand,prop_line,original_side,actual_strikeouts,market_result,source_workbook,source_url) VALUES ('2026-07-17','Gabriel Hughes','COL','CIN','R',4.5,NULL,6,'Over','tracker_master_closed_2026-07-18.xlsx','https://www.cbssports.com/mlb/gametracker/live/MLB_20260717_CIN%40COL/');
INSERT OR IGNORE INTO historical_archive_props(board_date,pitcher_name,team_abbreviation,opponent_abbreviation,pitcher_hand,prop_line,original_side,actual_strikeouts,market_result,source_workbook,source_url) VALUES ('2026-07-17','Brady Singer','CIN','COL','R',4.0,NULL,6,'Over','tracker_master_closed_2026-07-18.xlsx','https://www.cbssports.com/mlb/gametracker/live/MLB_20260717_CIN%40COL/');
INSERT OR IGNORE INTO historical_archive_props(board_date,pitcher_name,team_abbreviation,opponent_abbreviation,pitcher_hand,prop_line,original_side,actual_strikeouts,market_result,source_workbook,source_url) VALUES ('2026-07-17','Reid Detmers','LAA','DET','L',6.5,NULL,7,'Over','tracker_master_closed_2026-07-18.xlsx','https://www.cbssports.com/mlb/gametracker/live/MLB_20260717_DET%40LAA/');
INSERT OR IGNORE INTO historical_archive_props(board_date,pitcher_name,team_abbreviation,opponent_abbreviation,pitcher_hand,prop_line,original_side,actual_strikeouts,market_result,source_workbook,source_url) VALUES ('2026-07-17','Troy Melton','DET','LAA','R',5.5,NULL,9,'Over','tracker_master_closed_2026-07-18.xlsx','https://www.cbssports.com/mlb/gametracker/live/MLB_20260717_DET%40LAA/');
INSERT OR IGNORE INTO historical_archive_props(board_date,pitcher_name,team_abbreviation,opponent_abbreviation,pitcher_hand,prop_line,original_side,actual_strikeouts,market_result,source_workbook,source_url) VALUES ('2026-07-17','Merrill Kelly','AZ','STL','R',3.5,NULL,3,'Under','tracker_master_closed_2026-07-18.xlsx','https://www.cbssports.com/mlb/gametracker/live/MLB_20260717_STL%40ARI/');
INSERT OR IGNORE INTO historical_archive_props(board_date,pitcher_name,team_abbreviation,opponent_abbreviation,pitcher_hand,prop_line,original_side,actual_strikeouts,market_result,source_workbook,source_url) VALUES ('2026-07-17','Michael McGreevy','STL','AZ','R',3.5,NULL,5,'Over','tracker_master_closed_2026-07-18.xlsx','https://www.cbssports.com/mlb/gametracker/live/MLB_20260717_STL%40ARI/');
INSERT OR IGNORE INTO historical_archive_props(board_date,pitcher_name,team_abbreviation,opponent_abbreviation,pitcher_hand,prop_line,original_side,actual_strikeouts,market_result,source_workbook,source_url) VALUES ('2026-07-17','Gage Jump','ATH','WSH','L',5.0,NULL,8,'Over','tracker_master_closed_2026-07-18.xlsx','https://www.cbssports.com/mlb/gametracker/preview/MLB_20260717_WAS%40ATH/');
INSERT OR IGNORE INTO historical_archive_props(board_date,pitcher_name,team_abbreviation,opponent_abbreviation,pitcher_hand,prop_line,original_side,actual_strikeouts,market_result,source_workbook,source_url) VALUES ('2026-07-17','Cade Cavalli','WSH','ATH','R',5.0,NULL,9,'Over','tracker_master_closed_2026-07-18.xlsx','https://www.cbssports.com/mlb/gametracker/preview/MLB_20260717_WAS%40ATH/');
INSERT OR IGNORE INTO historical_archive_props(board_date,pitcher_name,team_abbreviation,opponent_abbreviation,pitcher_hand,prop_line,original_side,actual_strikeouts,market_result,source_workbook,source_url) VALUES ('2026-07-17','Landen Roupp','SF','SEA','R',5.5,NULL,2,'Under','tracker_master_closed_2026-07-18.xlsx','https://www.cbssports.com/mlb/gametracker/live/MLB_20260717_SF%40SEA/');
INSERT OR IGNORE INTO historical_archive_props(board_date,pitcher_name,team_abbreviation,opponent_abbreviation,pitcher_hand,prop_line,original_side,actual_strikeouts,market_result,source_workbook,source_url) VALUES ('2026-07-17','Bryce Miller','SEA','SF','R',6.0,NULL,6,'Push','tracker_master_closed_2026-07-18.xlsx','https://www.cbssports.com/mlb/gametracker/live/MLB_20260717_SF%40SEA/');
INSERT OR IGNORE INTO historical_archive_props(board_date,pitcher_name,team_abbreviation,opponent_abbreviation,pitcher_hand,prop_line,original_side,actual_strikeouts,market_result,source_workbook,source_url) VALUES ('2026-07-18','Gavin Williams','CLE','PIT','R',7.0,'More',11,'Over','tracker_master_closed_2026-07-18.xlsx','https://www.cbssports.com/mlb/gametracker/boxscore/MLB_20260718_PIT%40CLE/');
INSERT OR IGNORE INTO historical_archive_props(board_date,pitcher_name,team_abbreviation,opponent_abbreviation,pitcher_hand,prop_line,original_side,actual_strikeouts,market_result,source_workbook,source_url) VALUES ('2026-07-18','Jared Jones','PIT','CLE','R',5.0,'More',9,'Over','tracker_master_closed_2026-07-18.xlsx','https://www.cbssports.com/mlb/gametracker/boxscore/MLB_20260718_PIT%40CLE/');
INSERT OR IGNORE INTO historical_archive_props(board_date,pitcher_name,team_abbreviation,opponent_abbreviation,pitcher_hand,prop_line,original_side,actual_strikeouts,market_result,source_workbook,source_url) VALUES ('2026-07-18','Taj Bradley','MIN','CHC','R',6.0,'More',6,'Push','tracker_master_closed_2026-07-18.xlsx','https://www.cbssports.com/mlb/gametracker/boxscore/MLB_20260718_MIN%40CHC/');
INSERT OR IGNORE INTO historical_archive_props(board_date,pitcher_name,team_abbreviation,opponent_abbreviation,pitcher_hand,prop_line,original_side,actual_strikeouts,market_result,source_workbook,source_url) VALUES ('2026-07-18','Matthew Boyd','CHC','MIN','L',5.0,'More',4,'Under','tracker_master_closed_2026-07-18.xlsx','https://www.cbssports.com/mlb/gametracker/boxscore/MLB_20260718_MIN%40CHC/');
INSERT OR IGNORE INTO historical_archive_props(board_date,pitcher_name,team_abbreviation,opponent_abbreviation,pitcher_hand,prop_line,original_side,actual_strikeouts,market_result,source_workbook,source_url) VALUES ('2026-07-18','Davis Martin','CWS','TOR','R',4.0,'More',5,'Over','tracker_master_closed_2026-07-18.xlsx','https://www.cbssports.com/mlb/gametracker/boxscore/MLB_20260718_CHW%40TOR/');
INSERT OR IGNORE INTO historical_archive_props(board_date,pitcher_name,team_abbreviation,opponent_abbreviation,pitcher_hand,prop_line,original_side,actual_strikeouts,market_result,source_workbook,source_url) VALUES ('2026-07-18','Shane Bieber','TOR','CWS','R',5.0,'More',6,'Over','tracker_master_closed_2026-07-18.xlsx','https://www.cbssports.com/mlb/gametracker/boxscore/MLB_20260718_CHW%40TOR/');
INSERT OR IGNORE INTO historical_archive_props(board_date,pitcher_name,team_abbreviation,opponent_abbreviation,pitcher_hand,prop_line,original_side,actual_strikeouts,market_result,source_workbook,source_url) VALUES ('2026-07-18','Tomoyuki Sugano','COL','CIN','R',3.0,'More',3,'Push','tracker_master_closed_2026-07-18.xlsx','https://www.cbssports.com/mlb/gametracker/boxscore/MLB_20260718_CIN%40COL/');
INSERT OR IGNORE INTO historical_archive_props(board_date,pitcher_name,team_abbreviation,opponent_abbreviation,pitcher_hand,prop_line,original_side,actual_strikeouts,market_result,source_workbook,source_url) VALUES ('2026-07-18','Rhett Lowder','CIN','COL','R',3.0,'More',2,'Under','tracker_master_closed_2026-07-18.xlsx','https://www.cbssports.com/mlb/gametracker/boxscore/MLB_20260718_CIN%40COL/');
INSERT OR IGNORE INTO historical_archive_props(board_date,pitcher_name,team_abbreviation,opponent_abbreviation,pitcher_hand,prop_line,original_side,actual_strikeouts,market_result,source_workbook,source_url) VALUES ('2026-07-18','Sean Manaea','NYM','PHI','L',5.0,'More',7,'Over','tracker_master_closed_2026-07-18.xlsx','https://www.cbssports.com/mlb/gametracker/boxscore/MLB_20260718_NYM%40PHI/');
INSERT OR IGNORE INTO historical_archive_props(board_date,pitcher_name,team_abbreviation,opponent_abbreviation,pitcher_hand,prop_line,original_side,actual_strikeouts,market_result,source_workbook,source_url) VALUES ('2026-07-18','Jesús Luzardo','PHI','NYM','L',7.0,'More',7,'Push','tracker_master_closed_2026-07-18.xlsx','https://www.cbssports.com/mlb/gametracker/boxscore/MLB_20260718_NYM%40PHI/');
INSERT OR IGNORE INTO historical_archive_props(board_date,pitcher_name,team_abbreviation,opponent_abbreviation,pitcher_hand,prop_line,original_side,actual_strikeouts,market_result,source_workbook,source_url) VALUES ('2026-07-18','Ian Seymour','TB','BOS','L',5.0,'More',4,'Under','tracker_master_closed_2026-07-18.xlsx','https://www.cbssports.com/mlb/gametracker/boxscore/MLB_20260718_TB%40BOS/');
INSERT OR IGNORE INTO historical_archive_props(board_date,pitcher_name,team_abbreviation,opponent_abbreviation,pitcher_hand,prop_line,original_side,actual_strikeouts,market_result,source_workbook,source_url) VALUES ('2026-07-18','Patrick Sandoval','BOS','TB','L',4.0,'More',5,'Over','tracker_master_closed_2026-07-18.xlsx','https://www.cbssports.com/mlb/gametracker/boxscore/MLB_20260718_TB%40BOS/');
INSERT OR IGNORE INTO historical_archive_props(board_date,pitcher_name,team_abbreviation,opponent_abbreviation,pitcher_hand,prop_line,original_side,actual_strikeouts,market_result,source_workbook,source_url) VALUES ('2026-07-18','Dustin May','STL','AZ','R',4.0,'More',6,'Over','tracker_master_closed_2026-07-18.xlsx','https://www.cbssports.com/mlb/gametracker/boxscore/MLB_20260718_STL%40ARI/');
INSERT OR IGNORE INTO historical_archive_props(board_date,pitcher_name,team_abbreviation,opponent_abbreviation,pitcher_hand,prop_line,original_side,actual_strikeouts,market_result,source_workbook,source_url) VALUES ('2026-07-18','Griffin Canning','SD','KC','R',4.0,'More',4,'Push','tracker_master_closed_2026-07-18.xlsx','https://www.cbssports.com/mlb/gametracker/boxscore/MLB_20260718_SD%40KC/');
INSERT OR IGNORE INTO historical_archive_props(board_date,pitcher_name,team_abbreviation,opponent_abbreviation,pitcher_hand,prop_line,original_side,actual_strikeouts,market_result,source_workbook,source_url) VALUES ('2026-07-18','Spencer Arrighetti','HOU','BAL','R',6.0,'More',6,'Push','tracker_master_closed_2026-07-18.xlsx','https://www.cbssports.com/mlb/gametracker/boxscore/MLB_20260718_BAL%40HOU/');
INSERT OR IGNORE INTO historical_archive_props(board_date,pitcher_name,team_abbreviation,opponent_abbreviation,pitcher_hand,prop_line,original_side,actual_strikeouts,market_result,source_workbook,source_url) VALUES ('2026-07-18','Owen Murphy','ATL','TEX','R',4.0,'More',2,'Under','tracker_master_closed_2026-07-18.xlsx','https://www.cbssports.com/mlb/gametracker/boxscore/MLB_20260718_TEX%40ATL/');
INSERT OR IGNORE INTO historical_archive_props(board_date,pitcher_name,team_abbreviation,opponent_abbreviation,pitcher_hand,prop_line,original_side,actual_strikeouts,market_result,source_workbook,source_url) VALUES ('2026-07-18','Brandon Pfaadt','AZ','STL','R',3.5,'More',3,'Under','tracker_master_closed_2026-07-18.xlsx','https://www.cbssports.com/mlb/gametracker/boxscore/MLB_20260718_STL%40ARI/');
INSERT OR IGNORE INTO historical_archive_props(board_date,pitcher_name,team_abbreviation,opponent_abbreviation,pitcher_hand,prop_line,original_side,actual_strikeouts,market_result,source_workbook,source_url) VALUES ('2026-07-18','Randy Dobnak','KC','SD','R',2.5,'More',3,'Over','tracker_master_closed_2026-07-18.xlsx','https://www.cbssports.com/mlb/gametracker/boxscore/MLB_20260718_SD%40KC/');
INSERT OR IGNORE INTO historical_archive_props(board_date,pitcher_name,team_abbreviation,opponent_abbreviation,pitcher_hand,prop_line,original_side,actual_strikeouts,market_result,source_workbook,source_url) VALUES ('2026-07-18','Trevor Rogers','BAL','HOU','L',4.5,'More',8,'Over','tracker_master_closed_2026-07-18.xlsx','https://www.cbssports.com/mlb/gametracker/boxscore/MLB_20260718_BAL%40HOU/');
INSERT OR IGNORE INTO historical_archive_props(board_date,pitcher_name,team_abbreviation,opponent_abbreviation,pitcher_hand,prop_line,original_side,actual_strikeouts,market_result,source_workbook,source_url) VALUES ('2026-07-18','MacKenzie Gore','TEX','ATL','L',5.5,'More',7,'Over','tracker_master_closed_2026-07-18.xlsx','https://www.cbssports.com/mlb/gametracker/boxscore/MLB_20260718_TEX%40ATL/');
INSERT OR IGNORE INTO historical_archive_props(board_date,pitcher_name,team_abbreviation,opponent_abbreviation,pitcher_hand,prop_line,original_side,actual_strikeouts,market_result,source_workbook,source_url) VALUES ('2026-07-18','Max Meyer','MIA','MIL','R',5.5,'More',5,'Under','tracker_master_closed_2026-07-18.xlsx','https://www.cbssports.com/mlb/gametracker/boxscore/MLB_20260718_MIA%40MIL/');
INSERT OR IGNORE INTO historical_archive_props(board_date,pitcher_name,team_abbreviation,opponent_abbreviation,pitcher_hand,prop_line,original_side,actual_strikeouts,market_result,source_workbook,source_url) VALUES ('2026-07-18','Shane Drohan','MIL','MIA','L',4.5,'More',9,'Over','tracker_master_closed_2026-07-18.xlsx','https://www.cbssports.com/mlb/gametracker/boxscore/MLB_20260718_MIA%40MIL/');
INSERT OR IGNORE INTO historical_archive_props(board_date,pitcher_name,team_abbreviation,opponent_abbreviation,pitcher_hand,prop_line,original_side,actual_strikeouts,market_result,source_workbook,source_url) VALUES ('2026-07-18','Bryan Woo','SEA','SF','R',5.5,'More',7,'Over','tracker_master_closed_2026-07-18.xlsx','https://www.cbssports.com/mlb/gametracker/boxscore/MLB_20260718_SF%40SEA/');
INSERT OR IGNORE INTO historical_archive_props(board_date,pitcher_name,team_abbreviation,opponent_abbreviation,pitcher_hand,prop_line,original_side,actual_strikeouts,market_result,source_workbook,source_url) VALUES ('2026-07-18','Logan Webb','SF','SEA','R',5.5,'More',5,'Under','tracker_master_closed_2026-07-18.xlsx','https://www.cbssports.com/mlb/gametracker/boxscore/MLB_20260718_SF%40SEA/');
INSERT OR IGNORE INTO historical_archive_props(board_date,pitcher_name,team_abbreviation,opponent_abbreviation,pitcher_hand,prop_line,original_side,actual_strikeouts,market_result,source_workbook,source_url) VALUES ('2026-07-18','Ryan Weathers','NYY','LAD','L',5.5,'More',NULL,'Void','tracker_master_closed_2026-07-18.xlsx','https://www.cbssports.com/mlb/gametracker/boxscore/MLB_20260718_LAD%40NYY/');
INSERT OR IGNORE INTO historical_archive_props(board_date,pitcher_name,team_abbreviation,opponent_abbreviation,pitcher_hand,prop_line,original_side,actual_strikeouts,market_result,source_workbook,source_url) VALUES ('2026-07-18','Emmet Sheehan','LAD','NYY','R',5.5,'More',NULL,'Void','tracker_master_closed_2026-07-18.xlsx','https://www.cbssports.com/mlb/gametracker/boxscore/MLB_20260718_LAD%40NYY/');
INSERT OR IGNORE INTO historical_archive_props(board_date,pitcher_name,team_abbreviation,opponent_abbreviation,pitcher_hand,prop_line,original_side,actual_strikeouts,market_result,source_workbook,source_url) VALUES ('2026-07-18','J.T. Ginn','ATH','WSH','R',4.0,'More',7,'Over','tracker_master_closed_2026-07-18.xlsx','https://www.cbssports.com/mlb/gametracker/boxscore/MLB_20260718_WAS%40ATH/');
INSERT OR IGNORE INTO historical_archive_props(board_date,pitcher_name,team_abbreviation,opponent_abbreviation,pitcher_hand,prop_line,original_side,actual_strikeouts,market_result,source_workbook,source_url) VALUES ('2026-07-18','Zack Littell','WSH','ATH','R',3.0,'More',4,'Over','tracker_master_closed_2026-07-18.xlsx','https://www.cbssports.com/mlb/gametracker/boxscore/MLB_20260718_WAS%40ATH/');
INSERT OR IGNORE INTO historical_archive_props(board_date,pitcher_name,team_abbreviation,opponent_abbreviation,pitcher_hand,prop_line,original_side,actual_strikeouts,market_result,source_workbook,source_url) VALUES ('2026-07-18','Grayson Rodriguez','LAA','DET','R',5.0,'More',3,'Under','tracker_master_closed_2026-07-18.xlsx','https://www.cbssports.com/mlb/gametracker/boxscore/MLB_20260718_DET%40LAA/');
INSERT OR IGNORE INTO historical_archive_props(board_date,pitcher_name,team_abbreviation,opponent_abbreviation,pitcher_hand,prop_line,original_side,actual_strikeouts,market_result,source_workbook,source_url) VALUES ('2026-07-18','Tarik Skubal','DET','LAA','L',8.5,'More',9,'Over','tracker_master_closed_2026-07-18.xlsx','https://www.cbssports.com/mlb/gametracker/boxscore/MLB_20260718_DET%40LAA/');

INSERT INTO audit_events (event_type, entity_type, event_details)
VALUES ('BUILD_4_1_6_INSTALLED','SYSTEM','{"release":"3.3","build":"4.1.6","feature":"Historical archive intake seeded from audited tracker result workbooks; separate from native props/snapshots"}');
