PRAGMA foreign_keys = ON;
CREATE TABLE IF NOT EXISTS statcast_challenger_replay_runs (
  statcast_replay_run_id INTEGER PRIMARY KEY AUTOINCREMENT,
  run_uuid TEXT NOT NULL UNIQUE,
  backtest_run_id INTEGER NOT NULL,
  backtest_dataset_build_id INTEGER NOT NULL,
  replay_version TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'RUNNING' CHECK(status IN ('RUNNING','SUCCEEDED','PARTIAL','FAILED')),
  started_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  completed_at TEXT,
  dates_completed INTEGER NOT NULL DEFAULT 0,
  rows_scored INTEGER NOT NULL DEFAULT 0,
  details_json TEXT NOT NULL DEFAULT '{}',
  FOREIGN KEY(backtest_run_id) REFERENCES backtest_runs(backtest_run_id),
  FOREIGN KEY(backtest_dataset_build_id) REFERENCES backtest_dataset_builds(backtest_dataset_build_id)
);
CREATE TABLE IF NOT EXISTS statcast_challenger_replay_dates (
  statcast_replay_date_id INTEGER PRIMARY KEY AUTOINCREMENT,
  statcast_replay_run_id INTEGER NOT NULL,
  board_date TEXT NOT NULL,
  status TEXT NOT NULL CHECK(status IN ('EXECUTED','SKIPPED','FAILED')),
  train_rows INTEGER NOT NULL DEFAULT 0,
  test_rows INTEGER NOT NULL DEFAULT 0,
  wins INTEGER NOT NULL DEFAULT 0,
  losses INTEGER NOT NULL DEFAULT 0,
  disagreements INTEGER NOT NULL DEFAULT 0,
  improved INTEGER NOT NULL DEFAULT 0,
  harmed INTEGER NOT NULL DEFAULT 0,
  details_json TEXT NOT NULL DEFAULT '{}',
  completed_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY(statcast_replay_run_id) REFERENCES statcast_challenger_replay_runs(statcast_replay_run_id) ON DELETE CASCADE,
  UNIQUE(statcast_replay_run_id,board_date)
);
CREATE TABLE IF NOT EXISTS statcast_challenger_replay_rows (
  statcast_replay_row_id INTEGER PRIMARY KEY AUTOINCREMENT,
  statcast_replay_run_id INTEGER NOT NULL,
  backtest_dataset_row_id INTEGER NOT NULL,
  board_date TEXT NOT NULL,
  pitcher_id INTEGER NOT NULL,
  pitcher_mlb_id INTEGER NOT NULL,
  pitcher_hand TEXT,
  prop_line REAL NOT NULL,
  model_edge REAL,
  baseline_side TEXT,
  baseline_outcome TEXT,
  baseline_hit INTEGER,
  challenger_side TEXT,
  challenger_probability REAL,
  challenger_outcome TEXT,
  challenger_hit INTEGER,
  challenger_play INTEGER NOT NULL DEFAULT 0,
  disagreement INTEGER NOT NULL DEFAULT 0,
  feature_quality_score REAL,
  games_lookback INTEGER,
  pitches_lookback INTEGER,
  whiff_rate REAL,
  swinging_strike_rate REAL,
  csw_rate REAL,
  chase_rate REAL,
  avg_fastball_velocity REAL,
  velocity_delta_30d REAL,
  avg_fastball_spin REAL,
  fastball_mix_share REAL,
  details_json TEXT NOT NULL DEFAULT '{}',
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY(statcast_replay_run_id) REFERENCES statcast_challenger_replay_runs(statcast_replay_run_id) ON DELETE CASCADE,
  FOREIGN KEY(backtest_dataset_row_id) REFERENCES backtest_dataset_rows_v3(backtest_dataset_row_id),
  FOREIGN KEY(pitcher_id) REFERENCES pitchers(pitcher_id),
  UNIQUE(statcast_replay_run_id,backtest_dataset_row_id)
);
CREATE INDEX IF NOT EXISTS idx_statcast_replay_rows_run_date ON statcast_challenger_replay_rows(statcast_replay_run_id,board_date);
CREATE INDEX IF NOT EXISTS idx_statcast_replay_dates_run_date ON statcast_challenger_replay_dates(statcast_replay_run_id,board_date);
INSERT INTO audit_events(event_type,entity_type,event_details) VALUES('BUILD_7_5_INSTALLED','SYSTEM','{"release":"3.6","build":"7.5","feature":"Statcast challenger chronological replay"}');
